Repository haas36u/spaceX, pull requests merged in 2018-05, with the labels that each got.

#5 Create endpoint for capsules
  src/app/app.component.ts
  src/app/models/capsule.ts
  src/app/services/spacex-api.service.ts
Labels: user-story

#7 Create endpoint for lauchpads
  src/app/models/launchpad.ts
  src/app/services/spacex-api.service.spec.ts
  src/app/services/spacex-api.service.ts
Labels: user-story

#10 Endpoint for core items
  src/app/models/core.ts
  src/app/models/launch.ts
  src/app/services/spacex-api.service.ts
Labels: enhancement, review

#13 #12: moved LaunchFilter
  src/app/models/launch.ts
  src/app/models/launchFilter.ts
  src/app/services/spacex-api.service.ts
Labels: review

#17 Rocket list
  src/app/components/rocket/rocket-list/rocket-list.component.css
  src/app/components/rocket/rocket-list/rocket-list.component.html
  src/app/components/rocket/rocket-list/rocket-list.component.ts
  src/app/components/rocket/rocket-thumb/rocket-thumb.component.css
  src/app/components/rocket/rocket-thumb/rocket-thumb.component.html
  src/app/components/rocket/rocket-thumb/rocket-thumb.component.ts
  src/app/modules/shared/shared.module.ts
Labels: review

#29 launch filters
  src/app/app.module.ts
  src/app/components/launch/launch-filter/launch-filter.component.css
  src/app/components/launch/launch-filter/launch-filter.component.html
  src/app/components/launch/launch-filter/launch-filter.component.spec.ts
  src/app/components/launch/launch-filter/launch-filter.component.ts
  src/app/components/launch/launch-list/launch-list.component.html
  src/app/components/launch/launch-list/launch-list.component.ts
  src/app/modules/shared/shared.module.ts
Labels: review

#36 Issues/33/launchpads
  src/app/components/launchpad/launchpad-details/launchpad-details.component.html
  src/app/components/launchpad/launchpad-details/launchpad-details.component.ts
  src/app/components/launchpad/launchpad-list/launchpad-list.component.html
  src/app/components/launchpad/launchpad-list/launchpad-list.component.ts
  src/app/components/launchpad/launchpad-thumb/launchpad-thumb.component.html
  src/app/components/launchpad/launchpad-thumb/launchpad-thumb.component.ts
  src/app/modules/app-routing/app-routing.module.ts
  src/styles.scss
Labels: enhancement
